# permissions for end users to view deployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: deployer
    app.kubernetes.io/managed-by: kustomize
  name: deployer-viewer-role
rules:
- apiGroups:
  - unicore.mcyou.cn
  resources:
  - deployers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - unicore.mcyou.cn
  resources:
  - deployers/status
  verbs:
  - get
