---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - unicore.mcyou.cn
  resources:
  - apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - unicore.mcyou.cn
  resources:
  - apps/finalizers
  verbs:
  - update
- apiGroups:
  - unicore.mcyou.cn
  resources:
  - apps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - unicore.mcyou.cn
  resources:
  - deployers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - unicore.mcyou.cn
  resources:
  - deployers/finalizers
  verbs:
  - update
- apiGroups:
  - unicore.mcyou.cn
  resources:
  - deployers/status
  verbs:
  - get
  - patch
  - update
