apiVersion: v1
kind: Service
metadata:
  name: basic-tidb-nodeport
  namespace: tidb
spec:
  type: NodePort
  ports:
    - name: mysql-client
      port: 30000
      targetPort: 4000
      nodePort: 32005
  selector:
    app.kubernetes.io/component: tidb
    app.kubernetes.io/instance: basic
    app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster