apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: unicore-local
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /var/unicore-mnt
provisioner: openebs.io/local
  # TODO Retain
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true