name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.22.0'
        
    - name: Cheak Go Version
      run: go version

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run Build
      run: make build
